### ISSUE TITLE
Add http routes for requesting the onlinestatus of users

### ISSUE THREAD

**Issue by oleggtro** [azuma-chat/azumaneo#10]
Basics are implemented but bulk requesting the status of all users on the instance and specifically requesting the status of a single user is still not possible. This issue will track the implementation of the above mentioned.

**Comment by okrplay** [comment]
The online status is not implemented at all in the new broker. Does it make sense to store the online status in the broker?

**Comment by oleggtro** [comment]
I am not sure. The chatserver held the onlinestatus, but it got deleted in [`b11650d`](https://github.com/azuma-chat/azumaneo/commit/b11650dccb5a5a1806975f64ab38645b918378ff?branch=b11650dccb5a5a1806975f64ab38645b918378ff&diff=split)... Maybe create an multipurpose actor that handles most of the other stuff that doesn't belong somewhere else?

**Comment by oleggtro** [comment]
Requesting the online status of individual users was implemented in [`29b39fe`](https://github.com/azuma-chat/azumaneo/commit/29b39fea7e3e9f33cf97699f3ca83fd4d9cbbb23).
