### ISSUE TITLE
Custom message broker

### ISSUE THREAD

**Issue by oleggtro** [azuma-chat/azumaneo#13]
We need a solution for subscribing the various `Ws` actors to the textchannels they have access to.

**Comment by oleggtro** [comment]
It should be able to handle actors subscribing and unsubscribing while running and subscribe to different structs used as messages (my solution for bringing the chatmessages to the actors would be to subscribe them to the channel ids).

**Comment by okrplay** [comment]
I've solved this with a basic pub-sub system where the subscribers are Actix websocket addresses and the topics are UUIDs in b11650dccb5a5a1806975f64ab38645b918378ff. Online status is currently missing completely, it will be tracked in issue #10.
