### ISSUE TITLE
Snowflake like ID system

### ISSUE THREAD

**Issue by oleggtro** [azuma-chat/azumaneo#4]
We need a snowflake like ID system for generating unique, but traceable IDs for messages...

**Comment by okrplay** [comment]
I would use UUIDs, as they're integrated into PostgreSQL already. What do you mean by traceable?

**Comment by oleggtro** [comment]
You can extract the timestamp of a message out of a given snowflake id. Maybe we can add an additional identifier for the sender/owner of the msg.

**Comment by okrplay** [comment]
I would store things like message sender in an additional property. UUIDv1 stores a creation timestamp and the MAC of the creator, UUIDv4 is completely random. With UUIDv4, we could just store a timestamp in an additional property.

**Comment by oleggtro** [comment]
We could, but with Snowflakes the client can calculate the timestamp itself what leads to less database utilization and a better experience for everyone online...

**Comment by okrplay** [comment]
What do you mean by that?

**Comment by oleggtro** [comment]
> To generate the roughly-sorted 64 bit ids in an uncoordinated manner, we settled on a composition of: timestamp, worker number and sequence number.

[Look at that](https://blog.twitter.com/engineering/en_us/a/2010/announcing-snowflake.html)

We need one less thing to store with snowflakes, because the timestamp is embedded into the id. If we're transmitting the ID anyway, we should be able to let the client calculate the timestamp itself.

**Comment by okrplay** [comment]
Of course, we could just store everything in the ID, even the user name, the profile picture etc. That just wouldn't be clean. I would use UUIDv1, those include timestamps and have the advantage over snowflakes that they're already built into PostgreSQL and that we won't have to implement that ourselves.

**Comment by oleggtro** [comment]
then let's just use uuidv1, I don't want to argue about that lol

**Comment by okrplay** [comment]
FYI: I opted for a random UUIDv4 and a separate timestamp in 582c354de3d286987417a57738f9939ccd9b5ae3, as this shouldn't noticeably decrease performance while being easier to process than combining ID and timestamp. If this causes problems, we should be able to easily migrate to a combined field.
