### ISSUE TITLE
Configuration loading

### ISSUE THREAD

**Issue by okrplay** [azuma-chat/azumaneo#6]
The host URI is currently pre-configured (with environment variable configuration commented out) and the database URL is taken from the environment variables. A fixed way to load configuration would be good. Possible options would include:

- Using dotenv (load either from environment variables or `.env` file, depends on which is present)
- Config file(s) (`toml`, `json`, `ron` etc.)
- Command line parameters

**Comment by oleggtro** [comment]
I usually prefer a config file...

**Comment by okrplay** [comment]
Yeah, me too. Which file format do you usually go for?

**Comment by oleggtro** [comment]
toml seems like a good choice here

**Comment by okrplay** [comment]
Absolutely agree on that, I'll take care of it.

**Comment by okrplay** [comment]
Introduced in b866a5dd9549f40be7a53811bff0ca77d4a98cd2
