### ISSUE TITLE
License missing

### ISSUE THREAD

**Issue by okrplay** [azuma-chat/azumaneo#7]
Azuma Neo is currently not using any license. Should we use a permissive or a restrictive license? [Choose a license](https://choosealicense.com/) may help deciding on one.

**Comment by oleggtro** [comment]
I have no idea... What would you choose?

**Comment by okrplay** [comment]
I usually go for a permissive license like MIT, but in this case the GPLv3 may also make sense as Azuma Neo is not really something you would or should integrate into a proprietary product, GPLv3 would prevent that by requiring you to disclose the source.

**Comment by oleggtro** [comment]
i know, but IF azuma really takes of, we would probably  lose all funding/dev help of big companies who could have interest in this...

**Comment by okrplay** [comment]
Huh, why? I'd be in favor for using the AGPLv3.

**Comment by oleggtro** [comment]
They would have to open source their code, which some companies can't without losing their income,

**Comment by okrplay** [comment]
They would have to open-source their changes to Azuma Neo. I don't see the problem with that, as Azuma Neo isn't really something you'd use as a dependency in a big project.

**Comment by oleggtro** [comment]
I know what you mean... Azuma Neo isn't supposed to be a library but a ready to use chatservice. AGPL is probably the best choice

**Comment by okrplay** [comment]
Exactly, that was my thought.

**Comment by okrplay** [comment]
Added in 6f757c4ce9a567cb294b7c1d7e4dea2392261f2c.
